"use client";

import Link from "next/link";
import { ArrowLeft, MessageCircle, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { StoreFooter, StoreHeader, whatsappLink } from "@/components/store-chrome";
import { useShop } from "@/components/shop-provider";
import { formatPrice, productBySlug } from "@/lib/products";
import { ProductImage } from "@/components/storefront";

export default function CartPage(){
  const {cart,removeFromCart,updateQuantity}=useShop(); const lines=cart.map(line=>({...line,product:productBySlug(line.slug)})).filter(line=>line.product); const subtotal=lines.reduce((sum,line)=>sum+(line.product?.price||0)*line.quantity,0); const shipping=subtotal===0||subtotal>=2999?0:199; const total=subtotal+shipping; const msg=`HEY I NEED ORDER\n\n${lines.map(l=>`${l.product?.name}\nSize: ${l.size}\nQuantity: ${l.quantity}\nPrice: ${formatPrice((l.product?.price||0)*l.quantity)}`).join("\n\n")}\n\nShipping: ${shipping?formatPrice(shipping):"FREE"}\nTotal: ${formatPrice(total)}`;
  return <main className="cart-page"><StoreHeader/><section className="page-hero"><p className="kicker">YOUR BAG</p><h1>Ready for<br/><em>game day.</em></h1></section>{lines.length===0?<section className="empty-cart"><ShoppingBag size={42}/><h2>Your bag is empty</h2><p>Find equipment built for your next session.</p><Link className="primary-cta" href="/">Shop equipment</Link></section>:<section className="cart-layout"><div className="cart-lines"><Link className="back-link" href="/"><ArrowLeft size={16}/> Continue shopping</Link>{lines.map(line=>line.product&&<article className="cart-line" key={`${line.slug}-${line.size}`}><ProductImage product={line.product}/><div><span>{line.product.sport}</span><h2>{line.product.name}</h2><p>Size / variant: <strong>{line.size}</strong></p><div className="quantity"><button onClick={()=>updateQuantity(line.slug,line.size,line.quantity-1)}><Minus size={15}/></button><span>{line.quantity}</span><button onClick={()=>updateQuantity(line.slug,line.size,line.quantity+1)}><Plus size={15}/></button></div></div><div className="line-total"><strong>{formatPrice(line.product.price*line.quantity)}</strong><button onClick={()=>removeFromCart(line.slug,line.size)} aria-label={`Remove ${line.product.name}`}><Trash2 size={17}/></button></div></article>)}</div><aside className="cart-summary"><p className="kicker">ORDER SUMMARY</p><div><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><div><span>Shipping</span><strong>{shipping?formatPrice(shipping):"FREE"}</strong></div><div className="grand-total"><span>Total</span><strong>{formatPrice(total)}</strong></div>{subtotal<2999&&<p>Add {formatPrice(2999-subtotal)} more for free shipping.</p>}<Link className="detail-buy" href="/checkout">Checkout</Link><a className="detail-whatsapp" href={whatsappLink(msg)} target="_blank" rel="noreferrer"><MessageCircle size={18}/> WhatsApp checkout</a></aside></section>}<StoreFooter/></main>;
}
