"use client";

import { useEffect, useMemo, useState } from "react";
import { Search, SlidersHorizontal, X } from "lucide-react";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { StoreFooter, StoreHeader } from "@/components/store-chrome";
import { ProductCard } from "@/components/storefront";
import { products } from "@/lib/products";

function Filters({category,setCategory,sport,setSport,size,setSize,rating,setRating,available,setAvailable,max,setMax}:{category:string;setCategory:(v:string)=>void;sport:string;setSport:(v:string)=>void;size:string;setSize:(v:string)=>void;rating:number;setRating:(v:number)=>void;available:boolean;setAvailable:(v:boolean)=>void;max:number;setMax:(v:number)=>void}){
  return <div className="search-filters"><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{[...new Set(products.map(p=>p.category))].map(v=><option key={v}>{v}</option>)}</select></label><label>Sport<select value={sport} onChange={e=>setSport(e.target.value)}><option>All</option><option>Cricket</option><option>Football</option></select></label><label>Size<select value={size} onChange={e=>setSize(e.target.value)}><option>All</option>{[...new Set(products.flatMap(p=>p.sizes))].map(v=><option key={v}>{v}</option>)}</select></label><label>Maximum price <strong>₹{max.toLocaleString("en-IN")}</strong><input type="range" min="500" max="8000" step="500" value={max} onChange={e=>setMax(Number(e.target.value))}/></label><label>Minimum rating<select value={rating} onChange={e=>setRating(Number(e.target.value))}><option value="0">All ratings</option><option value="4.7">4.7+</option><option value="4.8">4.8+</option></select></label><label className="check-filter"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/> In stock only</label></div>;
}

export default function SearchPage(){
  const [q,setQ]=useState("");const[category,setCategory]=useState("All");const[sport,setSport]=useState("All");const[size,setSize]=useState("All");const[rating,setRating]=useState(0);const[available,setAvailable]=useState(false);const[max,setMax]=useState(8000);
  useEffect(()=>{const id=window.setTimeout(()=>setQ(new URLSearchParams(window.location.search).get("q")||""),0);return()=>window.clearTimeout(id)},[]);
  const results=useMemo(()=>products.filter(p=>{const text=`${p.name} ${p.category} ${p.sport} ${p.brand} ${p.type}`.toLowerCase();return text.includes(q.toLowerCase())&&(category==="All"||p.category===category)&&(sport==="All"||p.sport===sport)&&(size==="All"||p.sizes.includes(size))&&p.price<=max&&p.rating>=rating&&(!available||p.stock>0)}),[q,category,sport,size,rating,available,max]);
  const clear=()=>{setQ("");setCategory("All");setSport("All");setSize("All");setRating(0);setAvailable(false);setMax(8000)};
  const filterProps={category,setCategory,sport,setSport,size,setSize,rating,setRating,available,setAvailable,max,setMax};
  return <main><StoreHeader/><section className="search-hero"><p className="kicker">FULL CATALOGUE</p><h1>Find your gear.</h1><div className="search-box"><Search size={22}/><input value={q} onChange={e=>setQ(e.target.value)} autoFocus placeholder="Search products, sports, brands or gear types" aria-label="Search products"/>{q&&<button onClick={()=>setQ("")} aria-label="Clear search"><X size={18}/></button>}</div></section><section className="search-body"><aside className="search-sidebar"><div className="filter-title"><strong>Filters</strong><button onClick={clear}>Clear all</button></div><Filters {...filterProps}/></aside><div className="search-results"><div className="search-results-head"><p><strong>{results.length}</strong> products {q&&<>matching “{q}”</>}</p><Sheet><SheetTrigger asChild><button className="filter-trigger"><SlidersHorizontal size={17}/> Filters</button></SheetTrigger><SheetContent side="bottom" className="filter-sheet"><SheetHeader><SheetTitle>Filter products</SheetTitle></SheetHeader><Filters {...filterProps}/></SheetContent></Sheet></div>{results.length?<div className="product-grid">{results.map(p=><ProductCard key={p.slug} product={p}/>)}</div>:<div className="no-results"><Search size={38}/><h2>No gear found</h2><p>Try a broader product name or clear a few filters.</p><button onClick={clear}>Clear filters</button></div>}</div></section><StoreFooter/></main>;
}
