import { notFound } from "next/navigation";
import { StoreFooter, StoreHeader } from "@/components/store-chrome";

const content:Record<string,{title:string;intro:string;sections:[string,string][]}>={
  shipping:{title:"Shipping policy",intro:"Clear delivery expectations for every Nitin Sports order.",sections:[["Order processing","Orders are confirmed on WhatsApp before dispatch. In-stock orders are usually prepared within 1–2 business days."],["Delivery coverage","We deliver across serviceable Indian pincodes. Delivery timing and any location-specific charges are confirmed before payment."],["Tracking","Once dispatched, tracking details are shared using the contact details supplied with your order."]]},
  returns:{title:"Return policy",intro:"A straightforward process when eligible gear is not right.",sections:[["Return window","Contact us within 7 days of delivery for unused items in their original packaging."],["Non-returnable items","Customized teamwear, personalized goods and items showing use cannot be returned unless they arrive defective."],["Start a return","Share your order details and clear product photos on WhatsApp. Eligibility and the return address will be confirmed there."]]},
  privacy:{title:"Privacy policy",intro:"How customer information is handled during ordering.",sections:[["Information collected","We use the contact, delivery and order details you provide to confirm, fulfill and support your purchase."],["How it is used","Information is used only for order communication, delivery coordination and customer support unless you separately consent otherwise."],["Your choices","You may ask us on WhatsApp to correct or remove order-related contact information, subject to legal recordkeeping duties."]]},
  terms:{title:"Terms & conditions",intro:"The practical terms that govern use of this store.",sections:[["Product information","Images are illustrative. Available colours, specifications and stock are confirmed before an order is accepted."],["Pricing and payment","Displayed prices are in Indian rupees. Final totals, delivery charges and payment instructions are confirmed on WhatsApp."],["Custom orders","Teamwear production begins after design, size, quantity, price and payment terms are approved. Customized items cannot normally be cancelled after production begins."]]}
};
export function generateStaticParams(){return Object.keys(content).map(policy=>({policy}));}
export default async function PolicyPage({params}:{params:Promise<{policy:string}>}){const{policy}=await params;const page=content[policy];if(!page)notFound();return <main><StoreHeader/><article className="policy-page"><p className="kicker">NITIN SPORTS</p><h1>{page.title}</h1><p className="policy-intro">{page.intro}</p>{page.sections.map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}</article><StoreFooter/></main>}
