"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Lock, MessageCircle } from "lucide-react";
import { StoreHeader, whatsappLink } from "@/components/store-chrome";
import { useShop } from "@/components/shop-provider";
import { formatPrice, productBySlug } from "@/lib/products";

export default function CheckoutPage(){
  const {cart}=useShop(); const [direct,setDirect]=useState<{slug:string;size:string;quantity:number}|null>(null);
  useEffect(()=>{const id=window.setTimeout(()=>{const p=new URLSearchParams(window.location.search);const slug=p.get("product");if(slug)setDirect({slug,size:p.get("size")||productBySlug(slug)?.sizes[0]||"Standard",quantity:Number(p.get("quantity")||1)});},0);return()=>window.clearTimeout(id)},[]);
  const lines=useMemo(()=>{const source=direct?[direct]:cart;return source.map(line=>({...line,product:productBySlug(line.slug)})).filter(l=>l.product)},[cart,direct]);
  const subtotal=lines.reduce((sum,l)=>sum+(l.product?.price||0)*l.quantity,0); const shipping=subtotal===0||subtotal>=2999?0:199; const total=subtotal+shipping;
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);const customer=[`Full Name: ${data.get("name")}`,`Mobile: ${data.get("mobile")}`,`WhatsApp: ${data.get("whatsapp")}`,`Email: ${data.get("email")}`,`Address: ${data.get("address")}, ${data.get("city")}, ${data.get("state")} - ${data.get("pincode")}`].join("\n");const order=lines.map(l=>`${l.product?.name} | Size: ${l.size} | Qty: ${l.quantity} | ${formatPrice((l.product?.price||0)*l.quantity)}`).join("\n");window.open(whatsappLink(`HEY I NEED ORDER\n\nCUSTOMER DETAILS\n${customer}\n\nPRODUCT DETAILS\n${order}\n\nShipping: ${shipping?formatPrice(shipping):"FREE"}\nTOTAL AMOUNT: ${formatPrice(total)}`),"_blank","noopener,noreferrer")};
  return <main className="checkout-page"><StoreHeader/><div className="checkout-wrap"><Link className="back-link" href="/cart"><ArrowLeft size={16}/> Back to cart</Link><div className="checkout-heading"><div><p className="kicker">SECURE CHECKOUT</p><h1>Finish your<br/><em>order.</em></h1></div><span><Lock size={16}/> Your details are only used to prepare this WhatsApp order.</span></div>{lines.length===0?<div className="empty-cart"><h2>No products selected</h2><Link className="primary-cta" href="/">Shop equipment</Link></div>:<div className="checkout-grid"><form onSubmit={submit} className="checkout-form"><h2>Delivery details</h2><div className="form-grid"><label>Full name<input name="name" required autoComplete="name"/></label><label>Mobile number<input name="mobile" required inputMode="tel" pattern="[0-9+ -]{8,15}" autoComplete="tel"/></label><label>WhatsApp number<input name="whatsapp" required inputMode="tel" pattern="[0-9+ -]{8,15}"/></label><label>Email<input name="email" type="email" required autoComplete="email"/></label><label className="full">Complete address<textarea name="address" required rows={3} autoComplete="street-address"/></label><label>City<input name="city" required autoComplete="address-level2"/></label><label>State<input name="state" required autoComplete="address-level1"/></label><label>Pincode<input name="pincode" required inputMode="numeric" pattern="[0-9]{6}" autoComplete="postal-code"/></label></div><button className="place-order" type="submit"><MessageCircle size={19}/> Place order on WhatsApp</button><p className="form-note">No online payment is collected. Availability, delivery timeline and payment instructions will be confirmed on WhatsApp.</p></form><aside className="checkout-summary"><p className="kicker">YOUR ORDER</p>{lines.map(l=><div className="checkout-line" key={`${l.slug}-${l.size}`}><span>{l.quantity}×</span><p>{l.product?.name}<small>{l.size}</small></p><strong>{formatPrice((l.product?.price||0)*l.quantity)}</strong></div>)}<div className="summary-totals"><div><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><div><span>Shipping</span><strong>{shipping?formatPrice(shipping):"FREE"}</strong></div><div><span>Total</span><strong>{formatPrice(total)}</strong></div></div></aside></div>}</div></main>;
}
